import { Product, Category, Table } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'All', icon: 'LayoutGrid', count: 235 },
  { 
    id: 'breakfast', 
    name: 'Breakfast', 
    icon: 'Coffee', 
    count: 19,
    banner: 'https://images.unsplash.com/photo-1493770348161-369560ae357d?w=1200&h=400&fit=crop'
  },
  { 
    id: 'soups', 
    name: 'Soups', 
    icon: 'Soup', 
    count: 6,
    banner: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200&h=400&fit=crop'
  },
  { 
    id: 'pasta', 
    name: 'Pasta', 
    icon: 'Utensils', 
    count: 14,
    banner: 'https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=1200&h=400&fit=crop'
  },
  { 
    id: 'main', 
    name: 'Main Course', 
    icon: 'ChefHat', 
    count: 62,
    banner: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1200&h=400&fit=crop'
  },
  { 
    id: 'burgers', 
    name: 'Burgers', 
    icon: 'Beef', 
    count: 13,
    banner: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=1200&h=400&fit=crop'
  },
  { 
    id: 'pizza', 
    name: 'Pizza', 
    icon: 'Pizza', 
    count: 24,
    banner: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&h=400&fit=crop'
  },
  { 
    id: 'desserts', 
    name: 'Desserts', 
    icon: 'IceCream', 
    count: 18,
    banner: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=1200&h=400&fit=crop'
  },
  { 
    id: 'drinks', 
    name: 'Drinks', 
    icon: 'GlassWater', 
    count: 45,
    banner: 'https://images.unsplash.com/photo-1544145945-f904253d0c7b?w=1200&h=400&fit=crop'
  },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Tasty Vegetable Salad Healthy Diet',
    description: 'A fresh mix of seasonal vegetables, organic greens, and our signature lemon-tahini dressing.',
    price: 17.99,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    isVeg: true,
    discount: '20% Off',
  },
  {
    id: '2',
    name: 'Original Chess Meat Burger With Chips',
    description: 'Juicy beef patty topped with melted cheddar, fresh lettuce, and served with crispy golden chips.',
    price: 23.99,
    category: 'burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '3',
    name: 'Tacos Salsa With Chickens Grilled',
    description: 'Authentic Mexican style tacos with grilled chicken, spicy salsa, and fresh cilantro.',
    price: 14.99,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '4',
    name: 'Meat Sushi Maki With Tuna, Shirp And Other',
    description: 'Premium selection of fresh tuna and shrimp rolled with seasoned rice and seaweed.',
    price: 9.99,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '5',
    name: 'Fresh Orange Juice With Basil Seed No Sugar',
    description: '100% natural orange juice infused with basil seeds for a refreshing and healthy boost.',
    price: 12.99,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1600266177646-1f63bbd4b22c?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '6',
    name: 'Original Chess Burger With French Fries',
    description: 'Classic cheeseburger with a perfectly grilled patty and a side of hot, salted french fries.',
    price: 10.59,
    category: 'burgers',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop',
    isVeg: false,
    discount: '20% Off',
  },
  {
    id: '7',
    name: 'Pepperoni Overload Pizza Large',
    description: 'Loaded with premium pepperoni slices and a blend of four cheeses on a crispy hand-tossed crust.',
    price: 19.99,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '8',
    name: 'Creamy Mushroom Pasta with Herbs',
    description: 'Al dente pasta tossed in a rich, creamy mushroom sauce with fresh parsley and parmesan.',
    price: 15.50,
    category: 'pasta',
    image: 'https://images.unsplash.com/photo-1645112481338-35627be96306?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '9',
    name: 'Chocolate Lava Cake with Vanilla Ice Cream',
    description: 'Warm chocolate cake with a molten center, served with a scoop of premium vanilla bean ice cream.',
    price: 8.99,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '10',
    name: 'Classic Margherita Pizza with Basil',
    description: 'Simple and elegant with fresh mozzarella, tomato sauce, and aromatic basil leaves.',
    price: 14.99,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbad80ad50?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '11',
    name: 'Iced Caramel Macchiato Large',
    description: 'Rich espresso combined with milk and vanilla-flavored syrup, topped with a caramel drizzle.',
    price: 6.50,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '12',
    name: 'Spicy Ramen with Soft Boiled Egg',
    description: 'Savory broth with chewy noodles, spicy chili oil, and a perfectly soft-boiled marinated egg.',
    price: 13.99,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '13',
    name: 'Avocado Toast with Poached Egg',
    description: 'Creamy mashed avocado on toasted sourdough, topped with a perfectly poached egg and red pepper flakes.',
    price: 11.99,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '14',
    name: 'Grilled Salmon with Asparagus',
    description: 'Fresh Atlantic salmon fillet grilled to perfection, served with tender asparagus and a lemon butter sauce.',
    price: 24.50,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop',
    isVeg: false,
    discount: '15% Off',
  },
  {
    id: '15',
    name: 'Strawberry Cheesecake Slice',
    description: 'Creamy New York style cheesecake on a graham cracker crust, topped with fresh strawberry compote.',
    price: 7.99,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '16',
    name: 'Double Patty BBQ Bacon Burger',
    description: 'Two juicy beef patties, crispy bacon, melted cheese, and tangy BBQ sauce on a toasted brioche bun.',
    price: 18.99,
    category: 'burgers',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '17',
    name: 'Classic Caesar Salad with Croutons',
    description: 'Crisp romaine lettuce, crunchy croutons, and creamy Caesar dressing, topped with shaved parmesan.',
    price: 12.50,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '18',
    name: 'Spicy Buffalo Wings with Blue Cheese',
    description: 'Crispy chicken wings tossed in spicy buffalo sauce, served with cool blue cheese dressing and celery.',
    price: 14.99,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '19',
    name: 'Four Cheese Ravioli with Pesto',
    description: 'Handmade ravioli filled with a blend of four cheeses, served in a vibrant basil pesto sauce.',
    price: 16.99,
    category: 'pasta',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '20',
    name: 'Hawaiian Pizza with Ham and Pineapple',
    description: 'The classic tropical combination of sweet pineapple and savory ham on a cheesy tomato base.',
    price: 18.50,
    category: 'pizza',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '21',
    name: 'Tiramisu with Espresso and Cocoa',
    description: 'Traditional Italian dessert with layers of coffee-soaked ladyfingers and creamy mascarpone cheese.',
    price: 9.50,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '22',
    name: 'Fresh Watermelon Mojito Mocktail',
    description: 'Refreshing blend of fresh watermelon, mint, lime, and soda water for a perfect summer drink.',
    price: 7.99,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '23',
    name: 'Crispy Fish and Chips with Tartar',
    description: 'Beer-battered white fish fillets served with thick-cut chips and our house-made tartar sauce.',
    price: 19.99,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1524339102455-67be5440371b?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '24',
    name: 'Blueberry Pancakes with Maple Syrup',
    description: 'Fluffy buttermilk pancakes bursting with fresh blueberries, served with pure maple syrup.',
    price: 13.99,
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '25',
    name: 'Mushroom Swiss Burger with Truffle Oil',
    description: 'Gourmet burger with sautéed mushrooms, melted Swiss cheese, and a hint of luxurious truffle oil.',
    price: 16.50,
    category: 'burgers',
    image: 'https://images.unsplash.com/photo-1512152272829-e3139592d56f?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '26',
    name: 'Seafood Paella with Saffron Rice',
    description: 'Traditional Spanish rice dish loaded with shrimp, mussels, and squid, seasoned with saffron and herbs.',
    price: 28.99,
    category: 'main',
    image: 'https://images.unsplash.com/photo-1534080564607-c9275445f29a?w=400&h=300&fit=crop',
    isVeg: false,
  },
  {
    id: '27',
    name: 'Mango Sticky Rice with Coconut Milk',
    description: 'Sweet glutinous rice served with fresh ripe mango slices and a rich, salty-sweet coconut cream.',
    price: 8.50,
    category: 'desserts',
    image: 'https://images.unsplash.com/photo-1566454825481-4e48f80aa4d7?w=400&h=300&fit=crop',
    isVeg: true,
  },
  {
    id: '28',
    name: 'Hot Chocolate with Marshmallows',
    description: 'Rich and velvety hot cocoa topped with a generous serving of fluffy mini marshmallows.',
    price: 5.99,
    category: 'drinks',
    image: 'https://images.unsplash.com/photo-1544787210-2827448b313c?w=400&h=300&fit=crop',
    isVeg: true,
  }
];

export const TABLES: Table[] = [
  { id: 'T1', label: 'T1', waiter: 'Jacob Jones', items: 6, status: 'Kitchen' },
  { id: 'T2', label: 'T2', waiter: 'Bessie Co...', items: 6, status: 'Process' },
  { id: 'T3', label: 'T3', waiter: 'Ralph Edwa...', items: 6, status: 'Process' },
];
